version: "3.8"

services:
  application:
    container_name: ${CONTAINER_NAME?err}
    build:
      context: .
      dockerfile: dockerfile
    networks:
      - application
      - reverse-proxy
    environment:
      - REPO=${REPO?err}
      - TERM=linux

networks:
  application:
    name: ${CONTAINER_NAME?err}
  reverse-proxy:
    external: true
